// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwTkXEyeEMGKm4nbUFrlnqV9yRdLiCA1s',
    appId: '1:61162256236:web:fce86c37b06015ec53e549',
    messagingSenderId: '61162256236',
    projectId: 'jarnama02',
    authDomain: 'jarnama02.firebaseapp.com',
    storageBucket: 'jarnama02.appspot.com',
    measurementId: 'G-E1P690XR47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gno2mmmQAIzP_ZMBWz7mZ1O6AmzQ-tk',
    appId: '1:61162256236:android:5fc8eb158ddc7d1d53e549',
    messagingSenderId: '61162256236',
    projectId: 'jarnama02',
    storageBucket: 'jarnama02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6wT4S98mHcTx6PZRGeTjwwS_Cha5PiJQ',
    appId: '1:61162256236:ios:3505d668b68f0d8853e549',
    messagingSenderId: '61162256236',
    projectId: 'jarnama02',
    storageBucket: 'jarnama02.appspot.com',
    iosClientId: '61162256236-24sgvfuog1v0irbpvtha7717h9ak7nuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6wT4S98mHcTx6PZRGeTjwwS_Cha5PiJQ',
    appId: '1:61162256236:ios:3505d668b68f0d8853e549',
    messagingSenderId: '61162256236',
    projectId: 'jarnama02',
    storageBucket: 'jarnama02.appspot.com',
    iosClientId: '61162256236-24sgvfuog1v0irbpvtha7717h9ak7nuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama02',
  );
}
